#version: '2.27.0' #ibsolote

services:
        mongo-db-srv:
                image: mongo:5.0.27-focal
                container_name: mongo-db-con
                restart: always
                volumes:
                        - mongoVol:/data/db       
                environment:
                        MONGO_INITDB_ROOT_USERNAME: admin
                        MONGO_INITDB_ROOT_PASSWORD: admin

        mongo-exp-srv:
                image: mongo-express:1.0.2-20-alpine3.19
                container_name: mongo-exp-con
                ports:
                        - 8085:8081
                environment: 
                        ME_CONFIG_MONGODB_SERVER: mongo-db-con
                        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
                        ME_CONFIG_MONGODB_ADMINPASSWORD: admin
                        ME_CONFIG_BASICAUTH_USERNAME: admin1
                        ME_CONFIG_BASICAUTH_PASSWORD: admin1
                depends_on: 
                        - mongo-db-srv
networks:
        mongo-net:
                driver: bridge

volumes:
        mongoVol:
                external: true
